project_id  = "customer-transactions-demo"
region      = "europe-west1"
bucket_name = "gzo10-file-ingestion-demo"
landing_dataset_id = "file_ingestion_landing"
curated_dataset_id  = "cust_txn_insights"
dataflow_bucket_name = "gzo10-dataflow-temp"
